### ISSUE TITLE
teflon.v0.4.py IndexError: list index out of range

### ISSUE THREAD

**Issue by cecilelorrain** [jradrion/TEFLoN#1]

**Comment by jradrion** [comment]
Hi Cécile,

I noticed that you closed this issue on GitHub, were you able to resolve
it? Was it a formatting issue with the hierarchy file? I apologize as I
have not revisited this code is quite some time. Please let me know if you
are still running into errors and I will do my best to fix whatever the
issue may be.

Best regards,
Jeff

**Comment by cecilelorrain** [comment]
Dear Jeff, 

Thank you for your answer ! I found the right way to format the hierarchy file that's why I closed the post. 
TEFLoN is a very clever pipeline to assess TE insertions.

May I ask few specific questions ? 
1) The sequencing I am working on was made using 250nt reads making part of the read overlapping and the insert size standard deviation around 140nt. Do you think that could cause problem to have overlapping read pairs ? 
2) I was wondering how to set properly the -n1/-n2 parameters for teflon_collapse.py, do you have any suggestion ? (if I understood correctly in your paper n1 corresponds to ">3 reads in the focal subline" and n2 corresponds to ">5 reads in non-focal subline")

Thank you again,
Best,
Cécile

**Comment by jradrion** [comment]
Hi Cécile,

1) Overlapping read pairs are definitely not ideal, as teflon requires that
read pairs have one end map to the TE database and the other end map to the
reference and cannot discover TEs by split read mapping, but it could still
work provided enough reads in the distribution have ends separated far
enough apart that their primary mappings do not overlap. I've never
actually tested such a scenario, but I think it should reduce the chance
that you discover the location of new TEs in your samples. However, once
the insertion positions have been discovered, read overlap should have less
of an effect on estimating their allele frequencies. You might want to see
if their are any newer TE calling programs that use split-read mappers, as
that it probably the best way to address the TE calling problem now anyhow.

2) Given the fact that you will likely have fewer reads that are able to
locate new TE positions, I would initially set both of those parameters to
1. This should give you the most power to identify TEs, but will also
elevate the rate of false positives.

Jeff
