### ISSUE TITLE
Interpreting the breakpoint coordinates

### ISSUE THREAD

**Issue by pbasting** [jradrion/TEFLoN#7]
Hi @jradrion

I'm currently working on revamping and adding new TE detection methods to the [McClintock pipeline](https://github.com/bergmanlab/mcclintock) and am interested in integrating TEFLoN, I just have a few questions about interpreting the output. Specifically, I want to make sure I am interpreting the breakpoint coordinates correctly. 

* Are the coordinates 0-based or 1-based? I ask because TEFLoN can take a BED6 file as input which uses 0-based coordinates, and I'm not sure if this convention is maintained in the output genotype file
* Do the breakpoint positions indicate the final position in the reference genome before you see evidence of an insertion, or the position where you see the transition from reference to insertion?
  * for example: does a 5' breakpoint at position `10` mean you see split-read mapping like: `5 6 7 8 9 10 TE TE TE TE` or `5 6 7 8 9 TE TE TE TE`. My assumption is the former but I want to make sure.
* Am I correct in interpreting a prediction with a 5' breakpoint larger than the 3' breakpoint as a non-reference insertion with a TSD?
  * For example: does a prediction with a 5' breakpoint at `92` and a 3' breakpoint at `89` indicate there is a non-reference insertion with a TSD of length 4?
```bash
# genotype prediction
chrXVI  92  89  TY3     TY3    ....

# my interpretation
5' Breakpoint Evidence: 84 85 86 87 88 89 90 91 92 -- -- -- -- -- --
3' Breakpoint Evidence: -- -- -- -- -- 89 90 91 92 93 94 95 96 97 98
```
##
Ultimately, my goal is to convert the predictions from TEFLoN's genotype file to a BED format that contains the interval for non-reference insertion TSDs so I want to make sure I am interpreting the positions correctly so I'm not inadvertently making the predictions worse.

Thanks in advance for any help you can provide.

Best,

Preston

**Comment by jradrion** [comment]
Hi @pbasting,

Sounds good. I haven't spent much time with this code in recent years, but I just took another look through parts of it and I am nearly certain that I am giving you the correct responses.

> Are the coordinates 0-based or 1-based? 

0-based

> Do the breakpoint positions indicate the final position in the reference genome before you see evidence of an insertion, or the position where you see the transition from reference to insertion? 

It should be the former, as the last mapped position adjacent to start of soft-clipping. 

> Am I correct in interpreting a prediction with a 5' breakpoint larger than the 3' breakpoint as a non-reference insertion with a TSD? 

Yes, it is consistent with the presence of a TSD (of length 4 in your example). The usual caveat applies that it could also be caused by mapping error.

I hope this helps. Feel free to ask any other questions and I'll do my best to answer.

Jeff

**Comment by pbasting** [comment]
Thanks Jeff, that's very helpful! I'll let you know if anything else comes up.
